version: '3.0'

services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./application/backend-app:/symfony
    container_name: ${PROJECT_NAME}-nginx
    restart: always
    depends_on:
      - php-fpm
    ports:
      - "8000:80"
    
  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./application/backend-app:/symfony
    container_name: ${PROJECT_NAME}-php-fpm
    environment:
      PG_PORT: ${PG_PORT}
      PG_HOST: ${PG_HOST}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_USER: ${PG_USER}
      PG_DATABASE: ${PG_DATABASE}
    depends_on:
      - postgres
    expose:
      - "9000"

  postgres:
    image: 'postgres:13.1-alpine'
    container_name: ${PROJECT_NAME}-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}