version: '3.0'

networks:
  main:
    driver: bridge
    ipam:
      config:
        - subnet: 10.6.0.0/16
          gateway: 10.6.0.1

services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./application/backend-app:/symfony
      - ./application/frontend-app:/react
    container_name: ${PROJECT_NAME}-nginx
    restart: always
    ports:
      - "80:80"
    networks:
      main:

  react:
    build:
      context: ./application/frontend-app
    volumes:
      - "./application/frontend-app:/react"
      - "/react/node_modules"
    container_name: ${PROJECT_NAME}-react
    depends_on:
      - php-fpm
      - nginx
    networks:
      main:
        ipv4_address: 10.6.1.2

  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./application/backend-app:/symfony
    container_name: ${PROJECT_NAME}-php-fpm
    environment:
      PG_PORT: ${PG_PORT}
      PG_HOST: ${PG_HOST}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_USER: ${PG_USER}
      PG_DATABASE: ${PG_DATABASE}
    depends_on:
      - postgres
      - nginx
    expose:
      - "9000"
    networks:
      main:

  postgres:
    image: 'postgres:13.1-alpine'
    container_name: ${PROJECT_NAME}-postgres
    volumes:
      - ./docker/postgres/data/:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    networks:
      main:
